config/routes.rb
Rails.application.routes.draw do
  get 'lease/index'
  get 'lease/start'
  get 'lease/download'

  get 'download', to: 'home#download'
  get 'start', to: 'home#start'
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def start
    water_affidavit = "#{Rails.root}/tmp/#{params[:owner]}-台水中間結帳切結書.png"
    electric = "#{Rails.root}/tmp/#{params[:owner]}-台電變更用電單.png"

    `ffmpeg -y \
      -i #{Rails.root}/app/assets/images/water-affidavit-letter.jpg \
      -vf "#{draw_text(params[:date], 55, 230, size: 30)},\
          #{draw_text(params[:owner], 280, 230, size: 30)},\
          #{draw_text(params[:waternum], 630, 250, size: 30)},\
          #{draw_text(params[:name], 980, 220, size: 30)},\
          #{draw_text(params[:phone], 1220, 220, size: 30)},\
          #{draw_text(params[:date], 1450, 220, size: 30)},\
          #{draw_text(params[:watervol], 60, 460, size: 30)},\
          #{draw_text(params[:address], 620, 400, size: 30)}" #{water_affidavit}`

    `ffmpeg -y \
      -i #{Rails.root}/app/assets/images/electric.png \
      -vf "#{draw_text(params[:address], 200, 228, size: 30)},\
            #{draw_text(params[:name], 300, 800, size: 30)},\
            #{draw_text(params[:idcard], 390, 840, size: 30)},\
            #{draw_text(params[:phone], 290, 880, size: 30)}" #{electric}`

    require 'zip'
    zip_name = "#{params[:address]}.zip"
    Zip::File.open("tmp/#{zip_name}", create: true) do |zip|
      zip.add(File.basename(water_affidavit), water_affidavit)
      zip.add(File.basename(electric), electric)
    end

    @name = zip_name
  ensure
    [water_affidavit, electric].each { |file| File.delete(file) }
  end

  def download
    name = CGI.unescape(params[:name])
    file = "tmp/#{name}"
    send_file(file) if File.exist?(file)
  ensure
    other_zips = Dir.glob("tmp/*.zip") - [file]
    other_zips.each { |file| File.delete(file) }
  end

  private

  def font_file
    "fontfile=#{Rails.root}/app/assets/fonts/TaipeiSansTCBeta-Regular.ttf"
  end

  def draw_text(text, x, y, color: 'black', size: 22)
    "drawtext=#{font_file}:text='#{text}':fontcolor=#{color}:fontsize=#{size}:x=#{x}:y=#{y}"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div>
    <h1 class="text-center mb-4">水電小幫手</h1>
    <p class="lead text-center">將協助冠甫，完成台水、台電需要填資料的雜事<br>只需要填一次資料，就產出所需圖片</p>
</div>

<%= form_with url: 'start', method: :get, class: 'row g-3' do |f| %>
    <div class="row g-3">
        <%= f.label '地址', class: 'form-label' %>
        <%= f.text_field :address, class: 'form-control' %>

        <%= f.label '日期' %>
        <%= f.text_field :date, class: 'form-control' %>

        <%= f.label '屋主' %>
        <%= f.text_field :owner, class: 'form-control' %>

        <%= f.label '姓名' %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label '身分證' %>
        <%= f.text_field :idcard, class: 'form-control' %>

        <%= f.label '電話' %>
        <%= f.text_field :phone, class: 'form-control' %>

        <%= f.label '水號' %>
        <%= f.text_field :waternum, class: 'form-control' %>

        <%= f.label '水表度數', class: 'watervol' %>
        <%= f.text_field :watervol, class: 'form-control' %>

        <%= f.submit '產生圖表', class: 'btn btn-primary mb-5' %>
    </div>
<% end %>

app/views/home/start.html.erb
<h1><u><%= params[:owner] %></u>的圖表產生完成</h1>
<p>共產生兩張圖，並且壓縮為一個檔案：</p>
<ol class="my-list">
    <li>台水 的 中間結帳切結書</li>
    <li>台電 的 變更用電單</li>
</ol>
<%= link_to '下載壓縮檔', download_path(name: @name), class: 'btn btn-primary mb-5' %>